# -*- coding: utf-8 -*-
"""KoGPT2_finetuning 외부정보 있는 것

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oSCDazkXETJnxBDHEuS46eWQNzEfdmNN
"""
from google.colab import drive
drive.mount('/content/drive')

import json

# 기존 파일
in_file = "/content/drive/MyDrive/finetune_data/item.json"  # 예시경로
# 저장할 파일
out_file = "/content/drive/MyDrive/finetune_data/item_text.json"

with open(in_file, "r", encoding="utf-8") as f:
    data = json.load(f)

result = []
for d in data:
    # "문서", "질문", "답변" 필드를 하나로 합침
    new_text = f"[문서]\n{d['문서']}\n\n[질문]\n{d['질문']}\n\n[답변]{d['답변']}"
    result.append({"text": new_text})

with open(out_file, "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

print(f"변환 완료! → {out_file}")

import json
import os
import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling

# ---------------------------
# 1) 경로 설정
# ---------------------------

# Colab에 업로드된 JSON 파일 경로를 지정하세요.
# 예: '/content/KoGPT2_finetuned_external_info.json'
FINETUNE_JSON = "/content/drive/MyDrive/finetune_data/item_text.json"

# 파인튜닝된 모델을 저장할 디렉터리 (Colab 내부)
OUTPUT_DIR = "/content/drive/MyDrive/kogpt2-refined-model"

# (Optional) GPU 디바이스 사용 여부 확인
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"► Training on device: {device}")

# ---------------------------
# 2) 토크나이저 & 모델 로드
# ---------------------------

# KoGPT2 토크나이저
# AutoTokenizer 로 바꿔야 vocab_file 관련 에러가 발생하지 않습니다.
tokenizer = AutoTokenizer.from_pretrained("skt/kogpt2-base-v2")
tokenizer.pad_token = tokenizer.eos_token  # pad_token을 eos_token으로 설정

model = AutoModelForCausalLM.from_pretrained("skt/kogpt2-base-v2").to(device)
model.resize_token_embeddings(len(tokenizer))  # 토큰 개수 변경 반영


# ---------------------------
# 3) 데이터셋 로드 및 전처리
# ---------------------------

# 3-1) JSON 파일 읽기
with open(FINETUNE_JSON, "r", encoding="utf-8") as f:
    raw_list = json.load(f)
print(f"► 전체 레코드 수: {len(raw_list)}")

# 3-2) Dataset으로 변환
# 각 레코드는 {"text": [..., ...]} 형태 (리스트 안에 줄별 문자열)
dataset = Dataset.from_list(raw_list)

# 3-3) 줄 리스트를 하나의 문자열로 합치는 함수
def merge_lines(example):
    # example["text"]가 ["줄1", "줄2", ...] 형태이므로, "\n"으로 이어붙입니다.
    joined = "\n".join(example["text"]).strip()
    return {"joined_text": joined}

# "text" 칼럼은 제거하고 "joined_text" 추가
dataset = dataset.map(merge_lines, remove_columns=["text"])

# 3-4) 토큰화 함수: "joined_text"를 토크나이저로 인코딩
def tokenize_function(example):
    return tokenizer(
        example["joined_text"],
        truncation=True,
        padding="max_length",
        max_length=512,
    )

# batched=True로 설정하면 배치 단위로 토큰화하여 처리 속도 향상
tokenized_dataset = dataset.map(tokenize_function, batched=True, remove_columns=["joined_text"])

# 3-5) Data Collator 설정 (Causal LM용)
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,  # KoGPT2는 causal LM이므로 False
)

# ---------------------------
# 4) TrainingArguments 설정
# ---------------------------

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    overwrite_output_dir=True,
    num_train_epochs=3,               # 원하시는 epoch 수로 변경 가능
    per_device_train_batch_size=12,
    warmup_steps=200,# GPU 메모리에 따라 조정 (예: 4~8)
    lr_scheduler_type="linear",
    learning_rate=2e-5,               # 학습률 (필요 시 실험 후 조정)
    weight_decay=0.01,
    logging_dir=f"{OUTPUT_DIR}/logs",
    logging_steps=100,
    save_strategy="epoch",            # 매 epoch마다 체크포인트 저장
    save_total_limit=3,               # 가장 최근 3개 체크포인트만 남김
    fp16=True,                        # GPU가 지원하면 FP16 사용
    report_to = [],
             # 검증 데이터셋 없이 학습 시 "no"
)

# ---------------------------
# 5) Trainer 생성 및 학습
# ---------------------------

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    tokenizer=tokenizer,
    data_collator=data_collator,
)

# 실제 학습 실행
trainer.train()

# 학습 완료 후 모델과 토크나이저 저장
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("🎉 파인튜닝 완료. 모델 및 토크나이저가 저장된 경로:")
print(OUTPUT_DIR)